backend:
  name: github
  repo: Agamendon/ppage
  branch: main

publish_mode: editorial_workflow
media_folder: "media/dynamic"
site_url: https://hambartsumov.netlify.app/

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    extension: md
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        date_format: "DD.MM.YYYY"
        format: "LL"
      - {label: "Body", name: "body", widget: "markdown"}
    preview_path: "/{{year}}/{{month}}/{{day}}/{{ slug | slice: 11, 100000 }}"

  - name: "index"
    label: "Index page"
    description: "The main page"
    extension: md
    slug: "index.{{extension}}"
    files:
      - label: "Main page"
        name: "main"
        file: "/index.md"
        fields:
          - {label: "Layout", name: "layout", widget: "hidden", default: "index"}
          - {label: Body, name: body, widget: markdown}